import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, mkdirSync, existsSync } from "fs";
import { resolve } from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Obsidian plugin target directory
const OBSIDIAN_PLUGIN_DIR = resolve(
  process.env.HOME || "",
  "Documents/Obsidian Vault/.obsidian/plugins/archive-x"
);

const RELEASE_DIR = resolve("release");

// Ensure directories exist
function ensureDir(dir) {
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
}

// Copy build artifacts to release and Obsidian plugin directory
function copyArtifacts() {
  const files = ["main.js", "manifest.json", "styles.css"];

  ensureDir(RELEASE_DIR);
  ensureDir(OBSIDIAN_PLUGIN_DIR);

  for (const file of files) {
    const src = resolve(file);
    if (existsSync(src)) {
      copyFileSync(src, resolve(RELEASE_DIR, file));
      copyFileSync(src, resolve(OBSIDIAN_PLUGIN_DIR, file));
      console.log(`  ✓ Copied ${file}`);
    }
  }

  console.log(`\n📦 Release output: ${RELEASE_DIR}`);
  console.log(`🔌 Plugin installed: ${OBSIDIAN_PLUGIN_DIR}\n`);
}

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
});

if (prod) {
  await context.rebuild();
  copyArtifacts();
  process.exit(0);
} else {
  await context.watch();
}
